const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    // GOOGLE Sign In
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',

    // EMAIL Sign In
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',

    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
};

export default UserActionTypes;